export const ALLOWED_RENDERER_KEYS = [
  "AUDIO_RECORDING",
  "AUDIO_PLAYBACK",
  "RECORD_RESPONSE",
  "SELECT_OPTION",
  "SELECT_OPTIONS",
  "OPTION_SELECTION",
  "ORDER_OPTIONS",
  "DRAG_AND_DROP",
  "DROPDOWN_SELECTION",
  "HIGHLIGHT_OPTIONS",
  "HIGHLIGHT_SELECTION",
  "HIGHLIGHT_TEXT",
  "TEXT_INPUT",
  "TEXT_RESPONSE",
  "READ_ALOUD_V1",
  "REPEAT_SENTENCE_V1",
  "DESCRIBE_IMAGE_V1",
  "RE_TELL_LECTURE_V1",
  "ANSWER_SHORT_QUESTION_V1",
  "RESPOND_TO_A_SITUATION_V1",
  "SUMMARIZE_GROUP_DISCUSSION_V1",
  "SUMMARIZE_WRITTEN_TEXT_V1",
  "WRITE_ESSAY_V1",
  "MC_READING_SINGLE_V1",
  "MC_READING_MULTIPLE_V1",
  "RE_ORDER_PARAGRAPHS_V1",
  "FILL_IN_THE_BLANKS_DRAG_AND_DROP_V1",
  "FILL_IN_THE_BLANKS_DROPDOWN_V1",
  "SUMMARIZE_SPOKEN_TEXT_V1",
  "MC_LISTENING_SINGLE_V1",
  "MC_LISTENING_MULTIPLE_V1",
  "FILL_IN_THE_BLANKS_TYPE_IN_V1",
  "HIGHLIGHT_CORRECT_SUMMARY_V1",
  "SELECT_MISSING_WORD_V1",
  "HIGHLIGHT_INCORRECT_WORDS_V1",
  "WRITE_FROM_DICTATION_V1",
 ] as const;

export type AllowlistedRendererKey = typeof ALLOWED_RENDERER_KEYS[number];

const ALLOWED_RENDERER_SET = new Set<string>(ALLOWED_RENDERER_KEYS);

const CLIENT_RUNTIME_RENDERERS = new Set<AllowlistedRendererKey>([
  "SUMMARIZE_WRITTEN_TEXT_V1",
  "WRITE_ESSAY_V1",
  "MC_READING_SINGLE_V1",
  "MC_READING_MULTIPLE_V1",
  "RE_ORDER_PARAGRAPHS_V1",
  "FILL_IN_THE_BLANKS_DRAG_AND_DROP_V1",
  "FILL_IN_THE_BLANKS_DROPDOWN_V1",
]);

export function allowlistedRendererKey(value: unknown): AllowlistedRendererKey | null {
  return typeof value === "string" && ALLOWED_RENDERER_SET.has(value)
    ? value as AllowlistedRendererKey : null;
}

export function isClientRuntimeSupported(value: unknown): value is AllowlistedRendererKey {
  return allowlistedRendererKey(value) !== null && CLIENT_RUNTIME_RENDERERS.has(value as AllowlistedRendererKey);
}
